In [10]:
#Task1
import pandas as pd
data = pd.read_csv("books_data.csv")
table = pd.DataFrame(data)
table

                   Название                    Автор  Год издания  Цена
0        Мастер и Маргарита          Михаил Булгаков         1967   550
1  Преступление и наказание        Федор Достоевский         1866   420
2                      1984            Джордж Оруэлл         1949   600
3                   Алхимик             Пауло Коэльо         1988   350
4               Война и мир              Лев Толстой         1869   800
5           Маленький принц  Антуан де Сент-Экзюпери         1943   300
6            Евгений Онегин         Александр Пушкин         1833   450
7              Три товарища        Эрих Мария Ремарк         1936   500
8                        Мы          Евгений Замятин         1920   380
9         Братья Карамазовы        Федор Достоевский         1880   700

In [11]:
average_price = table['Цена'].mean()
average_price

np.float64(505.0)

In [8]:
after_2015 = table[table['Год издания'] > 1900] #Mne gemini takoy csv vidal poetou bolshe 1900 sedlal
after_2015

             Название                    Автор  Год издания  Цена
0  Мастер и Маргарита          Михаил Булгаков         1967   550
2                1984            Джордж Оруэлл         1949   600
3             Алхимик             Пауло Коэльо         1988   350
5     Маленький принц  Антуан де Сент-Экзюпери         1943   300
7        Три товарища        Эрих Мария Ремарк         1936   500
8                  Мы          Евгений Замятин         1920   380

In [12]:
sort_by_price = table.sort_values(by='Цена', ascending=True)
sort_by_price

                   Название                    Автор  Год издания  Цена
5           Маленький принц  Антуан де Сент-Экзюпери         1943   300
3                   Алхимик             Пауло Коэльо         1988   350
8                        Мы          Евгений Замятин         1920   380
1  Преступление и наказание        Федор Достоевский         1866   420
6            Евгений Онегин         Александр Пушкин         1833   450
7              Три товарища        Эрих Мария Ремарк         1936   500
0        Мастер и Маргарита          Михаил Булгаков         1967   550
2                      1984            Джордж Оруэлл         1949   600
9         Братья Карамазовы        Федор Достоевский         1880   700
4               Война и мир              Лев Толстой         1869   800

In [15]:
#Task2
import pandas as pd
data = pd.read_csv('orders_data.csv')
table = pd.DataFrame(data)
table

   Номер заказа         Клиент        Дата     Сумма
0           101    Иванов И.И.  2023-10-01   1500.50
1           102    Петров П.П.  2023-10-02   2300.00
2           103   Сидоров С.С.  2023-10-05    850.00
3           104    Иванов И.И.  2023-10-10   4200.75
4           105   Смирнов А.А.  2023-10-12  11000.00
5           106  Кузнецов В.В.  2023-10-15    560.20
6           107    Петров П.П.  2023-10-20   3100.40
7           108   Лебедев Д.Д.  2023-10-25  12500.00

In [16]:
table.head(10) #Mne gemini vsego 7 vidal prosto

   Номер заказа         Клиент        Дата     Сумма
0           101    Иванов И.И.  2023-10-01   1500.50
1           102    Петров П.П.  2023-10-02   2300.00
2           103   Сидоров С.С.  2023-10-05    850.00
3           104    Иванов И.И.  2023-10-10   4200.75
4           105   Смирнов А.А.  2023-10-12  11000.00
5           106  Кузнецов В.В.  2023-10-15    560.20
6           107    Петров П.П.  2023-10-20   3100.40
7           108   Лебедев Д.Д.  2023-10-25  12500.00

In [17]:
result = table['Клиент'].value_counts()
result

Клиент
Иванов И.И.      2
Петров П.П.      2
Сидоров С.С.     1
Смирнов А.А.     1
Кузнецов В.В.    1
Лебедев Д.Д.     1
Name: count, dtype: int64

In [18]:
max = table['Сумма'].max()
max

12500.0

In [19]:
min = table['Сумма'].min()
min

560.2

In [ ]:
total = table['Сумма'].sum()
total

In [20]:
#Task3
import pandas as pd
data = pd.read_csv('products_data.csv')
table = pd.DataFrame(data)
table

         Продукт          Категория  Калории  Белки
0   Куриное филе               Мясо      110   23.0
1         Яблоко             Фрукты       52    0.3
2         Творог  Молочные продукты       97   18.0
3         Лосось               Рыба      208   20.0
4         Огурец              Овощи       15    0.8
5  Орехи грецкие              Орехи      654   15.0
6          Банан             Фрукты       89    1.1

In [21]:
more_than_300 = table[table['Калории'] > 300]
more_than_300

         Продукт Категория  Калории  Белки
5  Орехи грецкие     Орехи      654   15.0

In [22]:
avg_protein = table.groupby('Категория')['Белки'].mean()
avg_protein

Категория
Молочные продукты    18.0
Мясо                 23.0
Овощи                 0.8
Орехи                15.0
Рыба                 20.0
Фрукты                0.7
Name: Белки, dtype: float64

In [24]:
sorted = table.sort_values(by='Калории', ascending=True)
sorted

         Продукт          Категория  Калории  Белки
4         Огурец              Овощи       15    0.8
1         Яблоко             Фрукты       52    0.3
6          Банан             Фрукты       89    1.1
2         Творог  Молочные продукты       97   18.0
0   Куриное филе               Мясо      110   23.0
3         Лосось               Рыба      208   20.0
5  Орехи грецкие              Орехи      654   15.0

In [26]:
#Task4
import pandas as pd
data = pd.read_csv('work_hours_data.csv')
table = pd.DataFrame(data)
table

       Имя                Проект  Часы
0     Иван                  Сайт    12
1     Анна  Мобильное приложение    25
2     Иван           База данных     8
3    Мария                  Сайт    15
4     Анна                  Сайт    10
5  Дмитрий  Мобильное приложение    30
6    Мария           База данных    20
7     Иван  Мобильное приложение     5

In [27]:
total_by_employee = table.groupby('Имя')['Часы'].mean()
total_by_employee

Имя
Анна       17.500000
Дмитрий    30.000000
Иван        8.333333
Мария      17.500000
Name: Часы, dtype: float64

In [ ]:
total_by_project = table.groupby('Проект')['Часы'].mean()
total_by_project

In [38]:
total_hours = table.groupby('Имя')['Часы'].sum()
the_most_hardworking_guy = total_hours.idxmax()
the_most_hardworking_guy

35

In [39]:
#Task5
import pandas as pd
data = pd.read_csv('cinema_data.csv')
table = pd.DataFrame(data)
table

                 Фильм            Город  Проданные билеты
0               Дюна 2           Москва              1200
1           Опенгеймер           Москва               850
2               Дюна 2  Санкт-Петербург               900
3                Барби           Казань               450
4           Опенгеймер  Санкт-Петербург               700
5                Барби           Москва              1100
6               Дюна 2           Казань               300
7  Сто лет тому вперёд           Москва              1500

In [41]:
total_tickets_by_film = table.groupby('Фильм')['Проданные билеты'].sum()
total_tickets_by_film

Фильм
Барби                  1550
Дюна 2                 2400
Опенгеймер             1550
Сто лет тому вперёд    1500
Name: Проданные билеты, dtype: int64

In [42]:
total_tickets_by_city = table.groupby('Город')['Проданные билеты'].sum()
total_tickets_by_city

Город
Казань              750
Москва             4650
Санкт-Петербург    1600
Name: Проданные билеты, dtype: int64

In [47]:
result = table.groupby('Фильм')['Проданные билеты'].sum().idxmax()
result

'Дюна 2'